# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dan/Documents/c/c_train

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dan/Documents/c/c_train

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dan/Documents/c/c_train/CMakeFiles /home/dan/Documents/c/c_train/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dan/Documents/c/c_train/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ctests

# Build rule for target.
ctests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctests
.PHONY : ctests

# fast build rule for target.
ctests/fast:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/build
.PHONY : ctests/fast

arrays/array_func.o: arrays/array_func.c.o

.PHONY : arrays/array_func.o

# target to build an object file
arrays/array_func.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/arrays/array_func.c.o
.PHONY : arrays/array_func.c.o

arrays/array_func.i: arrays/array_func.c.i

.PHONY : arrays/array_func.i

# target to preprocess a source file
arrays/array_func.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/arrays/array_func.c.i
.PHONY : arrays/array_func.c.i

arrays/array_func.s: arrays/array_func.c.s

.PHONY : arrays/array_func.s

# target to generate assembly for a file
arrays/array_func.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/arrays/array_func.c.s
.PHONY : arrays/array_func.c.s

fun_pointers/func_pointers.o: fun_pointers/func_pointers.c.o

.PHONY : fun_pointers/func_pointers.o

# target to build an object file
fun_pointers/func_pointers.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/fun_pointers/func_pointers.c.o
.PHONY : fun_pointers/func_pointers.c.o

fun_pointers/func_pointers.i: fun_pointers/func_pointers.c.i

.PHONY : fun_pointers/func_pointers.i

# target to preprocess a source file
fun_pointers/func_pointers.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/fun_pointers/func_pointers.c.i
.PHONY : fun_pointers/func_pointers.c.i

fun_pointers/func_pointers.s: fun_pointers/func_pointers.c.s

.PHONY : fun_pointers/func_pointers.s

# target to generate assembly for a file
fun_pointers/func_pointers.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/fun_pointers/func_pointers.c.s
.PHONY : fun_pointers/func_pointers.c.s

functions/different_functions.o: functions/different_functions.c.o

.PHONY : functions/different_functions.o

# target to build an object file
functions/different_functions.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/functions/different_functions.c.o
.PHONY : functions/different_functions.c.o

functions/different_functions.i: functions/different_functions.c.i

.PHONY : functions/different_functions.i

# target to preprocess a source file
functions/different_functions.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/functions/different_functions.c.i
.PHONY : functions/different_functions.c.i

functions/different_functions.s: functions/different_functions.c.s

.PHONY : functions/different_functions.s

# target to generate assembly for a file
functions/different_functions.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/functions/different_functions.c.s
.PHONY : functions/different_functions.c.s

main/main.o: main/main.c.o

.PHONY : main/main.o

# target to build an object file
main/main.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/main/main.c.o
.PHONY : main/main.c.o

main/main.i: main/main.c.i

.PHONY : main/main.i

# target to preprocess a source file
main/main.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/main/main.c.i
.PHONY : main/main.c.i

main/main.s: main/main.c.s

.PHONY : main/main.s

# target to generate assembly for a file
main/main.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/main/main.c.s
.PHONY : main/main.c.s

recursion1/recur.o: recursion1/recur.c.o

.PHONY : recursion1/recur.o

# target to build an object file
recursion1/recur.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/recursion1/recur.c.o
.PHONY : recursion1/recur.c.o

recursion1/recur.i: recursion1/recur.c.i

.PHONY : recursion1/recur.i

# target to preprocess a source file
recursion1/recur.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/recursion1/recur.c.i
.PHONY : recursion1/recur.c.i

recursion1/recur.s: recursion1/recur.c.s

.PHONY : recursion1/recur.s

# target to generate assembly for a file
recursion1/recur.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/recursion1/recur.c.s
.PHONY : recursion1/recur.c.s

std_lib_object/std_lib_object.o: std_lib_object/std_lib_object.c.o

.PHONY : std_lib_object/std_lib_object.o

# target to build an object file
std_lib_object/std_lib_object.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/std_lib_object/std_lib_object.c.o
.PHONY : std_lib_object/std_lib_object.c.o

std_lib_object/std_lib_object.i: std_lib_object/std_lib_object.c.i

.PHONY : std_lib_object/std_lib_object.i

# target to preprocess a source file
std_lib_object/std_lib_object.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/std_lib_object/std_lib_object.c.i
.PHONY : std_lib_object/std_lib_object.c.i

std_lib_object/std_lib_object.s: std_lib_object/std_lib_object.c.s

.PHONY : std_lib_object/std_lib_object.s

# target to generate assembly for a file
std_lib_object/std_lib_object.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/std_lib_object/std_lib_object.c.s
.PHONY : std_lib_object/std_lib_object.c.s

strings/str_change.o: strings/str_change.c.o

.PHONY : strings/str_change.o

# target to build an object file
strings/str_change.c.o:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/strings/str_change.c.o
.PHONY : strings/str_change.c.o

strings/str_change.i: strings/str_change.c.i

.PHONY : strings/str_change.i

# target to preprocess a source file
strings/str_change.c.i:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/strings/str_change.c.i
.PHONY : strings/str_change.c.i

strings/str_change.s: strings/str_change.c.s

.PHONY : strings/str_change.s

# target to generate assembly for a file
strings/str_change.c.s:
	$(MAKE) -f CMakeFiles/ctests.dir/build.make CMakeFiles/ctests.dir/strings/str_change.c.s
.PHONY : strings/str_change.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ctests"
	@echo "... arrays/array_func.o"
	@echo "... arrays/array_func.i"
	@echo "... arrays/array_func.s"
	@echo "... fun_pointers/func_pointers.o"
	@echo "... fun_pointers/func_pointers.i"
	@echo "... fun_pointers/func_pointers.s"
	@echo "... functions/different_functions.o"
	@echo "... functions/different_functions.i"
	@echo "... functions/different_functions.s"
	@echo "... main/main.o"
	@echo "... main/main.i"
	@echo "... main/main.s"
	@echo "... recursion1/recur.o"
	@echo "... recursion1/recur.i"
	@echo "... recursion1/recur.s"
	@echo "... std_lib_object/std_lib_object.o"
	@echo "... std_lib_object/std_lib_object.i"
	@echo "... std_lib_object/std_lib_object.s"
	@echo "... strings/str_change.o"
	@echo "... strings/str_change.i"
	@echo "... strings/str_change.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

